# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('team', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('winner', models.CharField(choices=[('AN', 'Andrew'), ('CA', 'Candice'), ('LO', 'Louise'), ('BE', 'Benjamina'), ('JA', 'Jane'), ('LE', 'Lee'), ('KA', 'Kate'), ('MI', 'Michael'), ('RA', 'Rav'), ('SE', 'Selasi'), ('VA', 'Val'), ('TO', 'Tom')], max_length=2)),
                ('second', models.CharField(choices=[('AN', 'Andrew'), ('CA', 'Candice'), ('LO', 'Louise'), ('BE', 'Benjamina'), ('JA', 'Jane'), ('LE', 'Lee'), ('KA', 'Kate'), ('MI', 'Michael'), ('RA', 'Rav'), ('SE', 'Selasi'), ('VA', 'Val'), ('TO', 'Tom')], max_length=2)),
                ('third', models.CharField(choices=[('AN', 'Andrew'), ('CA', 'Candice'), ('LO', 'Louise'), ('BE', 'Benjamina'), ('JA', 'Jane'), ('LE', 'Lee'), ('KA', 'Kate'), ('MI', 'Michael'), ('RA', 'Rav'), ('SE', 'Selasi'), ('VA', 'Val'), ('TO', 'Tom')], max_length=2)),
                ('fourth', models.CharField(choices=[('AN', 'Andrew'), ('CA', 'Candice'), ('LO', 'Louise'), ('BE', 'Benjamina'), ('JA', 'Jane'), ('LE', 'Lee'), ('KA', 'Kate'), ('MI', 'Michael'), ('RA', 'Rav'), ('SE', 'Selasi'), ('VA', 'Val'), ('TO', 'Tom')], max_length=2)),
                ('fifth', models.CharField(choices=[('AN', 'Andrew'), ('CA', 'Candice'), ('LO', 'Louise'), ('BE', 'Benjamina'), ('JA', 'Jane'), ('LE', 'Lee'), ('KA', 'Kate'), ('MI', 'Michael'), ('RA', 'Rav'), ('SE', 'Selasi'), ('VA', 'Val'), ('TO', 'Tom')], max_length=2)),
                ('sixth', models.CharField(choices=[('AN', 'Andrew'), ('CA', 'Candice'), ('LO', 'Louise'), ('BE', 'Benjamina'), ('JA', 'Jane'), ('LE', 'Lee'), ('KA', 'Kate'), ('MI', 'Michael'), ('RA', 'Rav'), ('SE', 'Selasi'), ('VA', 'Val'), ('TO', 'Tom')], max_length=2)),
                ('seventh', models.CharField(choices=[('AN', 'Andrew'), ('CA', 'Candice'), ('LO', 'Louise'), ('BE', 'Benjamina'), ('JA', 'Jane'), ('LE', 'Lee'), ('KA', 'Kate'), ('MI', 'Michael'), ('RA', 'Rav'), ('SE', 'Selasi'), ('VA', 'Val'), ('TO', 'Tom')], max_length=2)),
                ('eighth', models.CharField(choices=[('AN', 'Andrew'), ('CA', 'Candice'), ('LO', 'Louise'), ('BE', 'Benjamina'), ('JA', 'Jane'), ('LE', 'Lee'), ('KA', 'Kate'), ('MI', 'Michael'), ('RA', 'Rav'), ('SE', 'Selasi'), ('VA', 'Val'), ('TO', 'Tom')], max_length=2)),
                ('nineth', models.CharField(choices=[('AN', 'Andrew'), ('CA', 'Candice'), ('LO', 'Louise'), ('BE', 'Benjamina'), ('JA', 'Jane'), ('LE', 'Lee'), ('KA', 'Kate'), ('MI', 'Michael'), ('RA', 'Rav'), ('SE', 'Selasi'), ('VA', 'Val'), ('TO', 'Tom')], max_length=2)),
                ('tenth', models.CharField(choices=[('AN', 'Andrew'), ('CA', 'Candice'), ('LO', 'Louise'), ('BE', 'Benjamina'), ('JA', 'Jane'), ('LE', 'Lee'), ('KA', 'Kate'), ('MI', 'Michael'), ('RA', 'Rav'), ('SE', 'Selasi'), ('VA', 'Val'), ('TO', 'Tom')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(to='fantasybakeoff.Team'),
        ),
    ]
