# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-02 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('league', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('winner', models.CharField(choices=[('JO', 'Josh'), ('NA', 'Nadiya'), ('EM', 'Emma')], max_length=2)),
                ('second', models.CharField(choices=[('JO', 'Josh'), ('NA', 'Nadiya'), ('EM', 'Emma')], max_length=2)),
                ('third', models.CharField(choices=[('JO', 'Josh'), ('NA', 'Nadiya'), ('EM', 'Emma')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(to='fantasybakeoff.Team'),
        ),
    ]
