# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('team', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created', models.BooleanField(default=True)),
                ('winner', models.CharField(choices=[('Andrew', 'Andrew'), ('Candice', 'Candice'), ('Louise', 'Louise'), ('Benjamina', 'Benjamina'), ('Jane', 'Jane'), ('Lee', 'Lee'), ('Kate', 'Kate'), ('Michael', 'Michael'), ('Rav', 'Rav'), ('Selasi', 'Selasi'), ('Val', 'Val'), ('Tom', 'Tom')], max_length=20)),
                ('second', models.CharField(choices=[('Andrew', 'Andrew'), ('Candice', 'Candice'), ('Louise', 'Louise'), ('Benjamina', 'Benjamina'), ('Jane', 'Jane'), ('Lee', 'Lee'), ('Kate', 'Kate'), ('Michael', 'Michael'), ('Rav', 'Rav'), ('Selasi', 'Selasi'), ('Val', 'Val'), ('Tom', 'Tom')], max_length=20)),
                ('third', models.CharField(choices=[('Andrew', 'Andrew'), ('Candice', 'Candice'), ('Louise', 'Louise'), ('Benjamina', 'Benjamina'), ('Jane', 'Jane'), ('Lee', 'Lee'), ('Kate', 'Kate'), ('Michael', 'Michael'), ('Rav', 'Rav'), ('Selasi', 'Selasi'), ('Val', 'Val'), ('Tom', 'Tom')], max_length=20)),
                ('fourth', models.CharField(choices=[('Andrew', 'Andrew'), ('Candice', 'Candice'), ('Louise', 'Louise'), ('Benjamina', 'Benjamina'), ('Jane', 'Jane'), ('Lee', 'Lee'), ('Kate', 'Kate'), ('Michael', 'Michael'), ('Rav', 'Rav'), ('Selasi', 'Selasi'), ('Val', 'Val'), ('Tom', 'Tom')], max_length=20)),
                ('fifth', models.CharField(choices=[('Andrew', 'Andrew'), ('Candice', 'Candice'), ('Louise', 'Louise'), ('Benjamina', 'Benjamina'), ('Jane', 'Jane'), ('Lee', 'Lee'), ('Kate', 'Kate'), ('Michael', 'Michael'), ('Rav', 'Rav'), ('Selasi', 'Selasi'), ('Val', 'Val'), ('Tom', 'Tom')], max_length=20)),
                ('sixth', models.CharField(choices=[('Andrew', 'Andrew'), ('Candice', 'Candice'), ('Louise', 'Louise'), ('Benjamina', 'Benjamina'), ('Jane', 'Jane'), ('Lee', 'Lee'), ('Kate', 'Kate'), ('Michael', 'Michael'), ('Rav', 'Rav'), ('Selasi', 'Selasi'), ('Val', 'Val'), ('Tom', 'Tom')], max_length=20)),
                ('seventh', models.CharField(choices=[('Andrew', 'Andrew'), ('Candice', 'Candice'), ('Louise', 'Louise'), ('Benjamina', 'Benjamina'), ('Jane', 'Jane'), ('Lee', 'Lee'), ('Kate', 'Kate'), ('Michael', 'Michael'), ('Rav', 'Rav'), ('Selasi', 'Selasi'), ('Val', 'Val'), ('Tom', 'Tom')], max_length=20)),
                ('eighth', models.CharField(choices=[('Andrew', 'Andrew'), ('Candice', 'Candice'), ('Louise', 'Louise'), ('Benjamina', 'Benjamina'), ('Jane', 'Jane'), ('Lee', 'Lee'), ('Kate', 'Kate'), ('Michael', 'Michael'), ('Rav', 'Rav'), ('Selasi', 'Selasi'), ('Val', 'Val'), ('Tom', 'Tom')], max_length=20)),
                ('nineth', models.CharField(choices=[('Andrew', 'Andrew'), ('Candice', 'Candice'), ('Louise', 'Louise'), ('Benjamina', 'Benjamina'), ('Jane', 'Jane'), ('Lee', 'Lee'), ('Kate', 'Kate'), ('Michael', 'Michael'), ('Rav', 'Rav'), ('Selasi', 'Selasi'), ('Val', 'Val'), ('Tom', 'Tom')], max_length=20)),
                ('tenth', models.CharField(choices=[('Andrew', 'Andrew'), ('Candice', 'Candice'), ('Louise', 'Louise'), ('Benjamina', 'Benjamina'), ('Jane', 'Jane'), ('Lee', 'Lee'), ('Kate', 'Kate'), ('Michael', 'Michael'), ('Rav', 'Rav'), ('Selasi', 'Selasi'), ('Val', 'Val'), ('Tom', 'Tom')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(to='fantasybakeoff.Team'),
        ),
    ]
