# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasybakeoff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='nineth',
            new_name='ninth',
        ),
    ]
