# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasybakeoff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
