# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasybakeoff', '0002_auto_20160818_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(default='josh.carr@cantab.net', max_length=150, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
