# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-05 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasybakeoff', '0003_auto_20160804_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='slug',
            field=models.SlugField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
