# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasybakeoff', '0004_league_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='slug',
        ),
    ]
