# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasybakeoff', '0005_remove_league_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
